### ISSUE TITLE
osx cocoa sys call alert

### ISSUE THREAD

**Issue by joeblew99** [achille-roussel/go-vu#14]
in github.com/achille-roussel/go-vu/driver/cocoa

````

# github.com/achille-roussel/go-vu/driver/cocoa
../driver/cocoa/cocoa.c:80:48: warning: 'kCTFontHorizontalOrientation' is deprecated: first deprecated in OS X 10.11 [-Wdeprecated-declarations]
/System/Library/Frameworks/CoreText.framework/Headers/CTFontDescriptor.h:186:5: note: 'kCTFontHorizontalOrientation' has been explicitly marked deprecated here
../driver/cocoa/cocoa.c:106:7: warning: 'kCTFontHorizontalOrientation' is deprecated: first deprecated in OS X 10.11 [-Wdeprecated-declarations]
/System/Library/Frameworks/CoreText.framework/Headers/CTFontDescriptor.h:186:5: note: 'kCTFontHorizontalOrientation' has been explicitly marked deprecated here
../driver/cocoa/cocoa.c:114:50: warning: 'kCTFontHorizontalOrientation' is deprecated: first deprecated in OS X 10.11 [-Wdeprecated-declarations]
/System/Library/Frameworks/CoreText.framework/Headers/CTFontDescriptor.h:186:5: note: 'kCTFontHorizontalOrientation' has been explicitly marked deprecated here
# github.com/achille-roussel/go-vu/driver/shiny
../driver/shiny/shiny.go:24: cannot use display literal (type display) as type "github.com/achille-roussel/go-vu/driver".Display in argument to f:
	display does not implement "github.com/achille-roussel/go-vu/driver".Display (missing NewClipboard method)
../driver/shiny/shiny.go:48: cannot use win (type window) as type "github.com/achille-roussel/go-vu/driver".Window in assignment:
	window does not implement "github.com/achille-roussel/go-vu/driver".Window (missing Display method)
../driver/shiny/shiny.go:115: unknown event.ChangeScreen field 'Density' in struct literal


```

**Comment by achille-roussel** [comment]
Hi @joeblew99, thanks for reporting and sorry for the compile errors.

I'm seeing two different things in your trace, one is the use of a deprecated Cocoa symbol, the other is an attempt to use the `shiny` backend.

For the first error, I'll fix it tonight it shouldn't be hard. I was working on a OS X 10.10 until now which is why I didn't catch that warning.

For the second error, this is more of a *known* issue for now, I attempt to be able to use different rendering *backends* including gomobile and shiny but I haven't had enough time to keep them up to date with other developments so building the examples for gomobile and shiny is expected to break right now.
All other examples using the `desktop` backend should be working tho, please let me know if that's not the case for you.

**Comment by achille-roussel** [comment]
I've fixed the deprecations warnings, I'll close this issue, please feel free to reopen if you're still seeing the problem.

**Comment by joeblew99** [comment]
Thanks. Really awesome project.
